spring:
  main:
    banner-mode: "off"
    
  datasource:
    url: "jdbc:h2:mem:test"
    username: "sa"

holon:
  jwt:
    issuer: "TestIssuer"
    sharedkey-base64: "X7Cukx67arP4UQSjPBC8zEkpht8hc4FZZwiIJIz2Fr0="
    
server:
  port: 8443
  ssl:
    key-store: "classpath:keystore.jks"
    key-store-password: "secret"
    key-password: "secret"
