spring:
  main:
    banner-mode: "off"
    
holon:
  swagger:
    version: "v1"
    title: "Swagger API groups"
    
    api-groups:
      - group-id: "products"
        resource-package: "com.holonplatform.example.jaxrs.swagger.products"
        description: "Products management API"
        path: docs/products
      - group-id: "customers"
        resource-package: "com.holonplatform.example.jaxrs.swagger.customers"
        description: "Customers management API"
        path: docs/customers
